import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { NeonAuthUIProvider, UserButton } from "@neondatabase/auth/react";
import Link from "next/link";
import { authClient } from "@/lib/auth/client";
import { TRPCReactProvider } from "@/trpc/client";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<NeonAuthUIProvider authClient={authClient} defaultTheme="dark">
			<TRPCReactProvider>
				<html
					suppressHydrationWarning
					lang="en"
					className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
				>
					<body className="min-h-full flex flex-col bg-background text-foreground">
						<header className="border-b border-border bg-surface/90 backdrop-blur">
							<div className="mx-auto flex h-16 w-full max-w-6xl items-center justify-between px-4">
								<Link href="/" className="text-sm font-semibold tracking-wide">
									Event Planner
								</Link>
								<nav className="flex items-center gap-4">
									<Link href="/dashboard" className="text-muted-foreground">
										Dashboard
									</Link>
									<UserButton size="icon" />
								</nav>
							</div>
						</header>
						<main>{children}</main>
					</body>
				</html>
			</TRPCReactProvider>
		</NeonAuthUIProvider>
	);
}
